[FAB-6415] Various chaincode deployment updates
Update to latest Docker Gradle plugin
 - Removes various build warnings.

Use Gradle wrapper (./gradlew) if present in chaincode
 - Enables chaincode developer to specify own Gradle version.

Remove v1.3 version of shim from Docker image
 - Why was this ever added? Certainly not needed for Fabric v2.0.

Add jitpack.io to generated Maven POM
 -Maven can't find the JSON dependencies.

Add support for Gradle build scripts written in Kotlin
 - Latest version of Gradle supports Kotlin build script, we need
   to check for this when trying to figure out what kind of project
   we're dealing with.

Enable JAR file deployment
 - If JARs are present and no Gradle/Maven files are present, then
   just use the JARs. Only works with new programming model.
   Significantly improves deployment time, as no compilation occurs.

Add tests for all of the above!

Signed-off-by: Simon Stone <sstone1@uk.ibm.com>
Change-Id: I66ba7bd433377f2ea87fe6bc3eb99231cd2fe761

diff --git a/fabric-chaincode-docker/start b/fabric-chaincode-docker/start
--- a/fabric-chaincode-docker/start
+++ b/fabric-chaincode-docker/start
@@ -1,69 +1,19 @@
 #!/usr/bin/env bash
+set -ex
 
-# Attempt to set APP_HOME
-# Resolve links: $0 may be a link
-PRG="$0"
-# Need this for relative symlinks.
-while [ -h "$PRG" ] ; do
-    ls=`ls -ld "$PRG"`
-    link=`expr "$ls" : '.*-> \(.*\)$'`
-    if expr "$link" : '/.*' > /dev/null; then
-        PRG="$link"
-    else
-        PRG=`dirname "$PRG"`"/$link"
+ROOT_DIR=/root/chaincode-java
+LIB_DIR=${ROOT_DIR}/lib
+CHAINCODE_DIR=${ROOT_DIR}/chaincode
+LIB_JARS=$(find ${LIB_DIR} -name "*.jar" | paste -s -d ":" -)
+CHAINCODE_JARS=$(find ${CHAINCODE_DIR} -name "*.jar" | paste -s -d ":" -)
+NUM_CHAINCODE_JARS=$(find ${CHAINCODE_DIR} -name "*.jar" | wc -l)
+
+if [ -f ${CHAINCODE_DIR}/.uberjar ]; then
+    if [ ${NUM_CHAINCODE_JARS} -ne 1 ]; then
+        >&2 echo "Cannot start uber JAR as more than one JAR file was found in the chaincode directory"
+        exit 255
     fi
-done
-SAVED="`pwd`"
-cd "`dirname \"$PRG\"`" >/dev/null
-APP_HOME="`pwd -P`"
-cd "$SAVED" >/dev/null
-
-APP_NAME="start"
-APP_BASE_NAME=`basename "$0"`
-
-# Use the maximum available, or set MAX_FD != -1 to use that value.
-MAX_FD="maximum"
-
-warn () {
-    echo "$*"
-}
-
-die () {
-    echo
-    echo "$*"
-    echo
-    exit 1
-}
-
-# Determine the Java command to use to start the JVM.
-if [ -n "$JAVA_HOME" ] ; then
-    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
-        # IBM's JDK on AIX uses strange locations for the executables
-        JAVACMD="$JAVA_HOME/jre/sh/java"
-    else
-        JAVACMD="$JAVA_HOME/bin/java"
-    fi
-    if [ ! -x "$JAVACMD" ] ; then
-        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
-
-Please set the JAVA_HOME variable in your environment to match the
-location of your Java installation."
-    fi
+    exec java -jar ${CHAINCODE_JARS} "$@"
 else
-    JAVACMD="java"
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
-
-Please set the JAVA_HOME variable in your environment to match the
-location of your Java installation."
+    exec java -cp ${CHAINCODE_JARS}:${LIB_JARS} org.hyperledger.fabric.contract.ContractRouter "$@"
 fi
-
-# Escape application args
-save () {
-    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
-    echo " "
-}
-APP_ARGS=$(save "$@")
-
-exec "$JAVACMD" -jar $APP_HOME/chaincode/chaincode.jar "$@"
-
-
